# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.9 on 2023-06-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0024_micrositesettings_alter_footer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="micrositesettings",
            name="site_theme",
            field=models.CharField(
                choices=[("mozilla", "Mozilla.org theme"), ("firefox", "Firefox theme")],
                default="mozilla",
                help_text="Choose the design theme for this site. Changes will be immediately applied - there is no preview",
                max_length=64,
            ),
        ),
    ]
