# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.9 on 2023-06-29 21:24

from django.db import migrations, models

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0025_alter_micrositesettings_site_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocoltestpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock(required=False)),
                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                    (
                        "cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-l-card-hero", "5-Card Hero layout"),
                                            ("mzp-l-card-quarter", "4-Card Layout"),
                                            ("mzp-l-card-third", "3-Card Layout"),
                                            ("mzp-l-card-half", "2-Card Layout"),
                                        ]
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "size",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("mzp-c-card-extra-small", "Extra small"),
                                                            ("", "Small"),
                                                            ("mzp-c-card-extra-medium", "Medium"),
                                                            ("mzp-c-card-large", "Large"),
                                                            ("mzp-c-card-extra-large", "Extra Large"),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Card title with about 30-40 characters", max_length=60, required=True
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="A description of about 150 characters. Usually we only have room for one or two sentences.",
                                                        max_length=170,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "cta",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Call to action with about 30-40 characters", max_length=60, required=False
                                                    ),
                                                ),
                                                (
                                                    "meta_info",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Meta info at the base of the card", max_length=60, required=False
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "image_aspect_ratio",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("mzp-has-aspect-1-1", "1:1"),
                                                            ("mzp-has-aspect-3-2", "3:2"),
                                                            ("mzp-has-aspect-16-9", "16:9"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "card_image",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                            (
                                                                "alt_text",
                                                                wagtail.blocks.CharBlock(
                                                                    label="Alt-text for this image", max_length=250, required=False
                                                                ),
                                                            ),
                                                            (
                                                                "decorative_only",
                                                                wagtail.blocks.BooleanBlock(
                                                                    default=False, label="Is this image decorative only?", required=False
                                                                ),
                                                            ),
                                                            (
                                                                "width",
                                                                wagtail.blocks.IntegerBlock(
                                                                    label="Specific image width in px (optional)", min_value=0, required=False
                                                                ),
                                                            ),
                                                            (
                                                                "height",
                                                                wagtail.blocks.IntegerBlock(
                                                                    label="Specific image height in px (optional)", min_value=0, required=False
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                ("tag", wagtail.blocks.CharBlock(max_length=48, required=False)),
                                            ]
                                        ),
                                        help_text="<a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                                    ),
                                ),
                            ],
                            help_text="Layout wrapper for Cards. <a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                            label="Card group",
                            required=False,
                        ),
                    ),
                    (
                        "split",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout_variant",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Standard"),
                                            ("mzp-l-split-reversed", "Reversed"),
                                            ("mzp-t-dark mzp-t-background-secondary", "Dark Background"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "content_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("mzp-t-content-md", "Medium"), ("mzp-t-content-lg", "Large"), ("mzp-t-content-xl", "Extra-large")],
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=120, required=True)),
                                ("text", wagtail.blocks.TextBlock(max_length=500, required=True)),
                                (
                                    "cta_button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50)),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                            (
                                                "decorative_only",
                                                wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                            ),
                                            (
                                                "width",
                                                wagtail.blocks.IntegerBlock(
                                                    label="Specific image width in px (optional)", min_value=0, required=False
                                                ),
                                            ),
                                            (
                                                "height",
                                                wagtail.blocks.IntegerBlock(
                                                    label="Specific image height in px (optional)", min_value=0, required=False
                                                ),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/split--default.html'>Protocol docs for split</a>.  Not all options supported",
                            label="Split content",
                            required=False,
                        ),
                    ),
                    (
                        "columns",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-l-content", "One column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-two", "Two column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-three", "Three column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-four", "Four column"),
                                        ]
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "picto",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "layout",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Standard"),
                                                                    ("mzp-t-picto-center", "Centered"),
                                                                    ("mzp-t-picto-side", "Side"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Alt-text for this image", max_length=250, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "decorative_only",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False, label="Is this image decorative only?", required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "width",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            label="Specific image width in px (optional)", min_value=0, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "height",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            label="Specific image height in px (optional)",
                                                                            min_value=0,
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                required=True,
                                                            ),
                                                        ),
                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "body",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                max_length=150,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        help_text="Only blocks that can fit/flow well in a multi-column layout are allowed here - e.g. Picto",
                                    ),
                                ),
                            ],
                            help_text="Column layout wrapper. <a href='https://protocol.mozilla.org/components/detail/columns--overview.html'>Protocol docs for columns</a>.. Has sub-components. <a href='https://protocol.mozilla.org/components/detail/picto--default.html'>Protocol docs for picto</a>.",
                            label="Column block",
                            required=False,
                        ),
                    ),
                    (
                        "article",
                        wagtail.blocks.StructBlock(
                            [
                                ("header", wagtail.blocks.CharBlock(help_text="Rendered as a H1", max_length=250)),
                                (
                                    "intro_para",
                                    wagtail.blocks.CharBlock(
                                        help_text="Rendered as a single styled paragraph element  (<p>). 2000 chars max, but less is better.",
                                        max_length=1000,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["blockquote", "bold", "code", "h2", "h3", "italic", "link", "ol", "strikethrough", "ul"]
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/article.html'>Protocol docs for article</a>.",
                            label="Article block",
                            required=False,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocoltestpage",
            name="page_layout",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mzp-l-content mzp-t-content-sm", "Small"),
                    ("mzp-l-content mzp-t-content-md", "Medium"),
                    ("mzp-l-content mzp-t-content-lg", "Large"),
                    ("mzp-l-content mzp-t-content-xl", "Extra Large"),
                ],
                default="mzp-l-content mzp-t-content-lg",
                help_text="Optional layout wrapper <i>– only for components that need one</i>. <a href='https://protocol.mozilla.org/components/detail/content-container--default.html'>Protocol docs for layout</a>.",
                max_length=64,
            ),
        ),
    ]
