# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.9 on 2023-06-30 11:15

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0026_alter_protocoltestpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="aftermatter",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                ("label", wagtail.blocks.CharBlock(max_length=100)),
                                            ]
                                        ),
                                        collapsed=True,
                                        max_num=10,
                                    ),
                                ),
                                ("legal_text", wagtail.blocks.RichTextBlock(features=["link"])),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Add one aftermatter block; this is important for legal links etc",
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="columns",
            field=wagtail.fields.StreamField(
                [
                    (
                        "grouped_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(label="Column title - e.g. 'Company' or 'Support'", max_length=50, required=False),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                ("label", wagtail.blocks.CharBlock(max_length=100)),
                                            ]
                                        ),
                                        collapsed=True,
                                    ),
                                ),
                            ],
                            label="Column of links",
                        ),
                    )
                ],
                blank=True,
                help_text="Add up to six columns of links OR five + social links",
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="social_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "socials",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Social links section title - e.g. 'Follow @mozilla'", max_length=50, required=False
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("firefox", "Firefox"),
                                                            ("github", "Github"),
                                                            ("instagram", "Instagram"),
                                                            ("linkedin", "LinkedIn"),
                                                            ("mastodon", "Mastodon"),
                                                            ("pocket", "Pocket"),
                                                            ("spotify", "Spotify"),
                                                            ("tiktok", "TikTok"),
                                                            ("twitter", "Twitter"),
                                                            ("youtube", "YouTube"),
                                                        ]
                                                    ),
                                                ),
                                                ("url", wagtail.blocks.URLBlock(required=True)),
                                                (
                                                    "data_label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='Service name and handle - e.g. "Twitter (@mozilla)"', max_length=50, required=True
                                                    ),
                                                ),
                                            ]
                                        ),
                                        collapsed=True,
                                        label="Social links",
                                        max_num=6,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Add an group of social links (optional)",
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocoltestpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock(required=False)),
                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                    (
                        "cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-l-card-hero", "5-Card Hero layout"),
                                            ("mzp-l-card-quarter", "4-Card Layout"),
                                            ("mzp-l-card-third", "3-Card Layout"),
                                            ("mzp-l-card-half", "2-Card Layout"),
                                        ]
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "size",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("mzp-c-card-extra-small", "Extra small"),
                                                            ("", "Small"),
                                                            ("mzp-c-card-extra-medium", "Medium"),
                                                            ("mzp-c-card-large", "Large"),
                                                            ("mzp-c-card-extra-large", "Extra Large"),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Card title with about 30-40 characters", max_length=60, required=True
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="A description of about 150 characters. Usually we only have room for one or two sentences.",
                                                        max_length=170,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "cta",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Call to action with about 30-40 characters", max_length=60, required=False
                                                    ),
                                                ),
                                                (
                                                    "meta_info",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Meta info at the base of the card", max_length=60, required=False
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "image_aspect_ratio",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("mzp-has-aspect-1-1", "1:1"),
                                                            ("mzp-has-aspect-3-2", "3:2"),
                                                            ("mzp-has-aspect-16-9", "16:9"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "card_image",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                            (
                                                                "alt_text",
                                                                wagtail.blocks.CharBlock(
                                                                    label="Alt-text for this image", max_length=250, required=False
                                                                ),
                                                            ),
                                                            (
                                                                "decorative_only",
                                                                wagtail.blocks.BooleanBlock(
                                                                    default=False, label="Is this image decorative only?", required=False
                                                                ),
                                                            ),
                                                            (
                                                                "width",
                                                                wagtail.blocks.IntegerBlock(
                                                                    label="Specific image width in px (optional)", min_value=0, required=False
                                                                ),
                                                            ),
                                                            (
                                                                "height",
                                                                wagtail.blocks.IntegerBlock(
                                                                    label="Specific image height in px (optional)", min_value=0, required=False
                                                                ),
                                                            ),
                                                            (
                                                                "rendition_spec",
                                                                wagtail.blocks.CharBlock(
                                                                    blank=False,
                                                                    default="original",
                                                                    help_text="Lots of options available. See <a href='https://docs.wagtail.org/en/stable/topics/images.html#available-resizing-methods'>Wagtail docs on image sizing</a> Defaults to 'original'",
                                                                    max_length=256,
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                ("tag", wagtail.blocks.CharBlock(max_length=48, required=False)),
                                            ]
                                        ),
                                        collapsed=True,
                                        help_text="<a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                                    ),
                                ),
                            ],
                            help_text="Layout wrapper for Cards. <a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                            label="Card group",
                            required=False,
                        ),
                    ),
                    (
                        "split",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout_variant",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Standard"),
                                            ("mzp-l-split-reversed", "Reversed"),
                                            ("mzp-t-dark mzp-t-background-secondary", "Dark Background"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "content_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("mzp-t-content-md", "Medium"), ("mzp-t-content-lg", "Large"), ("mzp-t-content-xl", "Extra-large")],
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=120, required=True)),
                                ("text", wagtail.blocks.TextBlock(max_length=500, required=True)),
                                (
                                    "cta_button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50)),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                            (
                                                "decorative_only",
                                                wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                            ),
                                            (
                                                "width",
                                                wagtail.blocks.IntegerBlock(
                                                    label="Specific image width in px (optional)", min_value=0, required=False
                                                ),
                                            ),
                                            (
                                                "height",
                                                wagtail.blocks.IntegerBlock(
                                                    label="Specific image height in px (optional)", min_value=0, required=False
                                                ),
                                            ),
                                            (
                                                "rendition_spec",
                                                wagtail.blocks.CharBlock(
                                                    blank=False,
                                                    default="original",
                                                    help_text="Lots of options available. See <a href='https://docs.wagtail.org/en/stable/topics/images.html#available-resizing-methods'>Wagtail docs on image sizing</a> Defaults to 'original'",
                                                    max_length=256,
                                                ),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/split--default.html'>Protocol docs for split</a>.  Not all options supported",
                            label="Split content",
                            required=False,
                        ),
                    ),
                    (
                        "columns",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column_layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-l-content", "One column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-two", "Two column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-three", "Three column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-four", "Four column"),
                                        ]
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "picto",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "layout",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Standard"),
                                                                    ("mzp-t-picto-center", "Centered"),
                                                                    ("mzp-t-picto-side", "Side"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Alt-text for this image", max_length=250, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "decorative_only",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False, label="Is this image decorative only?", required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "width",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            label="Specific image width in px (optional)", min_value=0, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "height",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            label="Specific image height in px (optional)",
                                                                            min_value=0,
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "rendition_spec",
                                                                        wagtail.blocks.CharBlock(
                                                                            blank=False,
                                                                            default="original",
                                                                            help_text="Lots of options available. See <a href='https://docs.wagtail.org/en/stable/topics/images.html#available-resizing-methods'>Wagtail docs on image sizing</a> Defaults to 'original'",
                                                                            max_length=256,
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                required=True,
                                                            ),
                                                        ),
                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "body",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                max_length=150,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            )
                                        ],
                                        help_text="Only blocks that can fit/flow well in a multi-column layout are allowed here - e.g. Picto",
                                    ),
                                ),
                            ],
                            help_text="Column layout wrapper. <a href='https://protocol.mozilla.org/components/detail/columns--overview.html'>Protocol docs for columns</a>.. Has sub-components. <a href='https://protocol.mozilla.org/components/detail/picto--default.html'>Protocol docs for picto</a>.",
                            label="Column block",
                            required=False,
                        ),
                    ),
                    (
                        "article",
                        wagtail.blocks.StructBlock(
                            [
                                ("header", wagtail.blocks.CharBlock(help_text="Rendered as a H1", max_length=250)),
                                (
                                    "intro_para",
                                    wagtail.blocks.CharBlock(
                                        help_text="Rendered as a single styled paragraph element  (<p>). 2000 chars max, but less is better.",
                                        max_length=1000,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["h2", "h3", "bold", "italic", "strikethrough", "code", "blockquote", "link", "ol", "ul"]
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/article.html'>Protocol docs for article</a>.",
                            label="Article block",
                            required=False,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
