# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.9 on 2023-07-06 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("microsite", "0028_alter_protocoltestpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterStandardMessages",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("locked", models.BooleanField(default=False, editable=False, verbose_name="locked")),
                ("locked_at", models.DateTimeField(editable=False, null=True, verbose_name="locked at")),
                ("form_error_email_invalid", models.CharField(default="Please enter a valid email address", max_length=150)),
                ("form_error_select_contry", models.CharField(default="Please select a country or region", max_length=150)),
                ("form_error_select_languge", models.CharField(default="Please select a language", max_length=150)),
                ("form_error_newsletter_checkbox", models.CharField(default="Please check at least one of the newsletter options", max_length=150)),
                ("form_error_privacy_policy", models.CharField(default="You must agree to the privacy notice", max_length=150)),
                (
                    "form_error_try_again_later",
                    models.CharField(default="We are sorry, but there was a problem with our system. Please try again later!", max_length=150),
                ),
                ("form_label_your_email_address", models.CharField(default="Your email address", max_length=150)),
                ("form_label_country", models.CharField(default="Country", max_length=150)),
                ("form_label_language", models.CharField(default="Language", max_length=150)),
                (
                    "form_label_info_sought",
                    models.CharField(default="I want information about:", max_length=150, verbose_name="Form label for 'I want information about:'"),
                ),
                ("form_label_format", models.CharField(default="Format", max_length=150)),
                (
                    "form_label_privacy",
                    models.CharField(
                        default='I’m okay with Mozilla handling my info as explained in <a href="https://www.mozilla.org/privacy/websites/">this Privacy Notice</a>',
                        max_length=150,
                    ),
                ),
                ("form_label_submit_label", models.CharField(default="Sign up now", max_length=150)),
                ("form_label_submit_note", models.CharField(default="We will only send you Mozilla-related information.", max_length=150)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="locked by",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Newsletter Standard Messages - only one must exist",
            },
        ),
    ]
