# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.10 on 2023-07-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("microsite", "0034_blogpage_alter_protocoltestpage_body_blogpagetag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page_layout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mzp-l-content mzp-t-content-sm", "Small"),
                            ("mzp-l-content mzp-t-content-md", "Medium"),
                            ("mzp-l-content mzp-t-content-lg", "Large"),
                            ("mzp-l-content mzp-t-content-xl", "Extra Large"),
                        ],
                        default="mzp-l-content mzp-t-content-lg",
                        help_text="Optional layout wrapper <i>– only for components that need one</i>. <a href='https://protocol.mozilla.org/components/detail/content-container--default.html'>Protocol docs for layout</a>.",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
