# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.10 on 2023-07-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0035_blogindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="feed_image_alt_text",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
