# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.10 on 2023-07-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0038_blogpage_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="read_more_cta_label",
            field=models.CharField(default="Read more", max_length=50),
        ),
    ]
