# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.10 on 2023-07-26 20:33

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0055_alter_micrositesettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="aftermatter",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                ("label", wagtail.blocks.CharBlock(max_length=100)),
                                            ]
                                        ),
                                        collapsed=False,
                                        max_num=10,
                                    ),
                                ),
                                ("legal_text", wagtail.blocks.RichTextBlock(features=["link"])),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Add one aftermatter block; this is important for legal links etc",
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="columns",
            field=wagtail.fields.StreamField(
                [
                    (
                        "grouped_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(label="Column title - e.g. 'Company' or 'Support'", max_length=50, required=False),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                ("label", wagtail.blocks.CharBlock(max_length=100)),
                                            ]
                                        ),
                                        collapsed=False,
                                    ),
                                ),
                            ],
                            label="Column of links",
                        ),
                    )
                ],
                blank=True,
                help_text="Add up to six columns of links OR five + social links",
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="social_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "socials",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Social links section title - e.g. 'Follow @mozilla'", max_length=50, required=False
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("firefox", "Firefox"),
                                                            ("github", "Github"),
                                                            ("instagram", "Instagram"),
                                                            ("linkedin", "LinkedIn"),
                                                            ("mastodon", "Mastodon"),
                                                            ("pocket", "Pocket"),
                                                            ("spotify", "Spotify"),
                                                            ("tiktok", "TikTok"),
                                                            ("twitter", "Twitter"),
                                                            ("youtube", "YouTube"),
                                                        ]
                                                    ),
                                                ),
                                                ("url", wagtail.blocks.URLBlock(required=True)),
                                                (
                                                    "data_label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text='Service name and handle - e.g. "Twitter (@mozilla)"', max_length=50, required=True
                                                    ),
                                                ),
                                            ]
                                        ),
                                        collapsed=False,
                                        label="Social links",
                                        max_num=6,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Add an group of social links (optional)",
                null=True,
                use_json_field=True,
            ),
        ),
    ]
