# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.11 on 2023-09-18 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("microsite", "0061_alter_blogpage_body_alter_generalpurposepage_content_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsletterStandardMessages",
            new_name="FormStandardMessages",
        ),
    ]
