# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0063_alter_generalpurposepage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="micrositesettings",
            name="navigation_theme",
            field=models.CharField(
                choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")],
                default="mzp-t-light",
                help_text="Choose the colour theme of the navigation. Changes will be immediately applied - there is no preview",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="micrositesettings",
            name="site_theme",
            field=models.CharField(
                choices=[("mozilla", "Mozilla.org theme"), ("firefox", "Firefox theme")],
                default="mozilla",
                help_text="Choose the design theme (typography, colours) for this site. Changes will be immediately applied - there is no preview",
                max_length=64,
            ),
        ),
    ]
