# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-09-21 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0064_alter_generalpurposepage_content_and_more"),
        ("microsite", "0065_alter_generalpurposepage_content"),
    ]

    operations = []
