# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-09-25 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0074_merge_20230925_1641"),
        ("microsite", "0075_alter_generalpurposepage_content_and_more"),
    ]

    operations = []
