# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-10-01 19:54

from django.db import migrations, models

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks

import common.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0083_alter_innovationscontentpage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpurposepage",
            name="intro",
            field=models.TextField(blank=True, help_text="Optional intro text below the page title", max_length=1500),
        ),
        migrations.AlterField(
            model_name="generalpurposepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "article",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=150, required=False)),
                                (
                                    "heading_level",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("h2", "Heading Level 2"), ("h3", "Heading Level 3"), ("h4", "Heading Level 4")],
                                        help_text="Remember to respect best practices around hierarchy of heading level: <a href='https://developer.mozilla.org/docs/Web/HTML/Element/Heading_Elements#usage_notes'>See MDN</a>",
                                    ),
                                ),
                                (
                                    "heading_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("", "Large"), ("mzp-u-title-md", "Medium"), ("mzp-u-title-sm", "Small")],
                                        help_text="Sets the display size of the heading independent of the heading level (h2, h3, or h4).",
                                        required=False,
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(blank=True, choices=[("", "Default"), ("t-align-center", "Center")], required=False),
                                ),
                                (
                                    "intro_para",
                                    wagtail.blocks.CharBlock(
                                        help_text="Rendered as a single styled paragraph element. 2000 chars max, but less is better.",
                                        max_length=1000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["h2", "h3", "bold", "italic", "strikethrough", "code", "blockquote", "link", "ol", "ul"]
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/article.html'>Protocol docs for article</a>.",
                            label="Article block",
                            label_format="Article: {header}",
                            required=False,
                        ),
                    ),
                    (
                        "biography_grid",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=150, required=False)),
                                (
                                    "heading_level",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("h2", "Heading Level 2"), ("h3", "Heading Level 3"), ("h4", "Heading Level 4")],
                                        help_text="Remember to respect best practices around hierarchy of heading level: <a href='https://developer.mozilla.org/docs/Web/HTML/Element/Heading_Elements#usage_notes'>See MDN</a>",
                                    ),
                                ),
                                (
                                    "heading_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("", "Large"), ("mzp-u-title-md", "Medium"), ("mzp-u-title-sm", "Small")],
                                        help_text="Sets the display size of the heading independent of the heading level (h2, h3, or h4).",
                                        required=False,
                                    ),
                                ),
                                ("standfirst", wagtail.blocks.TextBlock(max_length=500, required=False)),
                                ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                                (
                                    "people",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("name", wagtail.blocks.CharBlock(max_length=100)),
                                                (
                                                    "bio",
                                                    wagtail.blocks.RichTextBlock(features=["bold", "italic", "strikethrough", "link", "ol", "ul"]),
                                                ),
                                                (
                                                    "meta_info",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Supplementary contextual info, this person's dept or project",
                                                        max_length=50,
                                                        required=False,
                                                    ),
                                                ),
                                                ("website", wagtail.blocks.URLBlock(required=False)),
                                                (
                                                    "image",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                            (
                                                                "alt_text",
                                                                wagtail.blocks.CharBlock(
                                                                    label="Alt-text for this image", max_length=250, required=False
                                                                ),
                                                            ),
                                                            (
                                                                "decorative_only",
                                                                wagtail.blocks.BooleanBlock(
                                                                    default=False, label="Is this image decorative only?", required=False
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        collapsed=False,
                                    ),
                                ),
                            ],
                            label_format="Biography grid: {title}",
                            required=False,
                        ),
                    ),
                    (
                        "cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-l-card-hero", "5-Card Hero layout"),
                                            ("mzp-l-card-quarter", "4-Card Layout"),
                                            ("mzp-l-card-third", "3-Card Layout"),
                                            ("mzp-l-card-half", "2-Card Layout"),
                                        ]
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Card title with about 30-40 characters", max_length=60, required=False
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="A description of about 150 characters. Usually we only have room for one or two sentences.",
                                                        max_length=170,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "cta",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Call to action with about 30-40 characters", max_length=60, required=False
                                                    ),
                                                ),
                                                (
                                                    "meta_info",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Meta info at the base of the card", max_length=60, required=False
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                            (
                                                                "rel",
                                                                wagtail.blocks.CharBlock(
                                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                                    max_length=100,
                                                                    required=False,
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "size",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("mzp-c-card-extra-small", "Extra small"),
                                                            ("", "Small"),
                                                            ("mzp-c-card-extra-medium", "Medium"),
                                                            ("mzp-c-card-large", "Large"),
                                                            ("mzp-c-card-extra-large", "Extra Large"),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "image_aspect_ratio",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("mzp-has-aspect-1-1", "1:1"),
                                                            ("mzp-has-aspect-3-2", "3:2"),
                                                            ("mzp-has-aspect-16-9", "16:9"),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "card_image",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                            (
                                                                "alt_text",
                                                                wagtail.blocks.CharBlock(
                                                                    label="Alt-text for this image", max_length=250, required=False
                                                                ),
                                                            ),
                                                            (
                                                                "decorative_only",
                                                                wagtail.blocks.BooleanBlock(
                                                                    default=False, label="Is this image decorative only?", required=False
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                                ("tag", wagtail.blocks.CharBlock(max_length=48, required=False)),
                                            ]
                                        ),
                                        collapsed=True,
                                        help_text="<a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                                    ),
                                ),
                            ],
                            help_text="Layout wrapper for Cards. <a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                            label="Card group",
                            label_format="Card group",
                            required=False,
                        ),
                    ),
                    (
                        "captioned_image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                (
                                    "decorative_only",
                                    wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                ),
                                ("image_caption", wagtail.blocks.CharBlock(max_length=250, required=False)),
                                ("image_credit", wagtail.blocks.CharBlock(max_length=250, required=False)),
                            ],
                            label_format="Captioned image: {image_caption}",
                            required=False,
                        ),
                    ),
                    (
                        "columns",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                (
                                    "column_layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-l-content", "One column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-two", "Two column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-three", "Three column"),
                                            ("mzp-l-content mzp-l-columns mzp-t-columns-four", "Four column"),
                                        ]
                                    ),
                                ),
                                (
                                    "background_color",
                                    common.blocks.ColorBlock(
                                        help_text="For a solid block of colour. Use with a light/dark theme as appropriate, to ensure text is visible.",
                                        required=True,
                                    ),
                                ),
                                ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "stack_of_pictos",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        ("title", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "pictos",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "layout",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    ("", "Standard"),
                                                                                    ("mzp-t-picto-center", "Centered"),
                                                                                    ("mzp-t-picto-side", "Side"),
                                                                                ],
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "image",
                                                                            wagtail.blocks.StructBlock(
                                                                                [
                                                                                    (
                                                                                        "image",
                                                                                        wagtail.images.blocks.ImageChooserBlock(required=False),
                                                                                    ),
                                                                                    (
                                                                                        "alt_text",
                                                                                        wagtail.blocks.CharBlock(
                                                                                            label="Alt-text for this image",
                                                                                            max_length=250,
                                                                                            required=False,
                                                                                        ),
                                                                                    ),
                                                                                    (
                                                                                        "decorative_only",
                                                                                        wagtail.blocks.BooleanBlock(
                                                                                            default=False,
                                                                                            label="Is this image decorative only?",
                                                                                            required=False,
                                                                                        ),
                                                                                    ),
                                                                                ],
                                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                        (
                                                                            "body",
                                                                            wagtail.blocks.TextBlock(
                                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                                max_length=150,
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                                collapsed=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "picto",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "layout",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Standard"),
                                                                    ("mzp-t-picto-center", "Centered"),
                                                                    ("mzp-t-picto-side", "Side"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Alt-text for this image", max_length=250, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "decorative_only",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False, label="Is this image decorative only?", required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                required=True,
                                                            ),
                                                        ),
                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "body",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                max_length=150,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "picto_with_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "layout",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Standard"),
                                                                    ("mzp-t-picto-center", "Centered"),
                                                                    ("mzp-t-picto-side", "Side"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Alt-text for this image", max_length=250, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "decorative_only",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False, label="Is this image decorative only?", required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                required=True,
                                                            ),
                                                        ),
                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "body",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                max_length=150,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                                    ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                                    (
                                                                        "rel",
                                                                        wagtail.blocks.CharBlock(
                                                                            help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                                            max_length=100,
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    ("label", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.RichTextBlock(
                                                    features=["h3", "h4", "bold", "italic", "strikethrough", "link", "ol", "ul"]
                                                ),
                                            ),
                                        ],
                                        help_text="Only blocks that can fit/flow well in a multi-column layout are allowed here - e.g. Picto",
                                    ),
                                ),
                            ],
                            help_text="Column layout wrapper. <a href='https://protocol.mozilla.org/components/detail/columns--overview.html'>Protocol docs for columns</a>.. Has sub-components. <a href='https://protocol.mozilla.org/components/detail/picto--default.html'>Protocol docs for picto</a>.",
                            label="Column block",
                            label_format="Column block: {column_layout}",
                            required=False,
                        ),
                    ),
                    (
                        "callout",
                        wagtail.blocks.StructBlock(
                            [
                                ("headline", wagtail.blocks.CharBlock(help_text="Around 50 chars ideally. Max 100", max_length=100, required=True)),
                                ("body", wagtail.blocks.TextBlock(help_text="Around 150 chars ideally. Max 300", max_length=300, required=True)),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=True,
                                    ),
                                ),
                                ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/call-out--default.html'>Protocol docs for callout</a>.",
                            label_format="Callout (standard size): {headline}",
                            required=False,
                        ),
                    ),
                    (
                        "compact_callout",
                        wagtail.blocks.StructBlock(
                            [
                                ("headline", wagtail.blocks.CharBlock(help_text="Around 50 chars ideally. Max 100", max_length=100, required=True)),
                                ("body", wagtail.blocks.TextBlock(help_text="Around 150 chars ideally. Max 300", max_length=300, required=True)),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=True,
                                    ),
                                ),
                                ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/compact-call-out--default.html'>Protocol docs for compact-callout</a>.",
                            label_format="Compact callout: {headline}",
                            required=False,
                        ),
                    ),
                    (
                        "newsletter_form",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "newsletter",
                                    wagtail.blocks.MultipleChoiceBlock(
                                        choices=[
                                            ("about-addons", "Add-ons Developer Newsletter"),
                                            ("about-mozilla", "Mozilla Community"),
                                            ("ambassadors", "Firefox Student Ambassadors"),
                                            ("app-dev", "Developer Newsletter"),
                                            ("common-voice", "Common Voice"),
                                            ("developer-events", "Developer Events"),
                                            ("didthis-waitlist", "DidThis Waitlist"),
                                            ("firefox-accounts-journey", "Welcome emails"),
                                            ("firefox-desktop", "Firefox for desktop"),
                                            ("firefox-friends", "Firefox Friends"),
                                            ("firefox-ios", "Firefox iOS"),
                                            ("firefox-os", "Firefox OS smartphone owner?"),
                                            ("firefox-sweepstakes", "Firefox Sweepstakes"),
                                            ("firefox-welcome", "Firefox Welcome"),
                                            ("game-developer-conference", "Game Developer Conference"),
                                            ("graceland-waitlist", "Graceland Waitlist"),
                                            ("guardian-vpn-waitlist", "Mozilla VPN Waitlist"),
                                            ("hubs", "Hubs"),
                                            ("inhuman", "Inhuman Ads"),
                                            ("internet-health-report", "Internet Health Report"),
                                            ("knowledge-is-power", "Knowledge is Power"),
                                            ("maker-party", "Maker Party"),
                                            ("mdnplus", "MDN"),
                                            ("member-comm", "Firefox Membership: Community Minded"),
                                            ("member-idealo", "Firefox Membership: Ideologically Engaged"),
                                            ("member-tech", "Firefox Membership: Tech-Forward"),
                                            ("member-tk", "Firefox Membership: TK"),
                                            ("miti", "Mozilla Information Trust Initiative"),
                                            ("mixed-reality", "Mixed Reality"),
                                            ("mobile", "Firefox for Android"),
                                            ("monitor-waitlist", "Monitor Waitlist"),
                                            ("mozilla-accounts", "Firefox Accounts"),
                                            ("mozilla-ai-challenge", "Responsible AI Challenge"),
                                            ("mozilla-and-you", "Firefox News"),
                                            ("mozilla-fellowship-awardee-alumni", "Mozilla Fellowship & Awardee Alumni"),
                                            ("mozilla-festival", "Mozilla Festival"),
                                            ("mozilla-foundation", "Mozilla News"),
                                            ("mozilla-general", "Mozilla"),
                                            ("mozilla-innovation", "Innovation at Mozilla"),
                                            ("mozilla-leadership-network", "Mozilla Leadership Network"),
                                            ("mozilla-learning-network", "Mozilla Learning Network"),
                                            ("mozilla-phone", "Mozillians"),
                                            ("mozilla-rally", "Mozilla Rally News"),
                                            ("mozilla-social-waitlist", "Mozilla Social Waitlist"),
                                            ("mozilla-technology", "Mozilla Labs"),
                                            ("mozilla-welcome", "Mozilla Welcome"),
                                            ("open-innovation-challenge", "Open Innovation Challenge"),
                                            ("open-leadership", "Open Leadership"),
                                            ("relay-phone-masking-waitlist", "Relay Phone Masking Waitlist"),
                                            ("relay-vpn-bundle-waitlist", "Relay VPN Bundle Waitlist"),
                                            ("relay-waitlist", "Firefox Relay Waitlist"),
                                            ("security-privacy-news", "Security and Privacy News from Mozilla"),
                                            ("shape-web", "Shape of the Web"),
                                            ("take-action-for-the-internet", "Take Action for the Internet"),
                                            ("test-pilot", "New Product Testing"),
                                            ("view-source-conference-global", "View Source Conference Global"),
                                            ("view-source-conference-north-america", "View Source Conference North America"),
                                            ("webmaker", "Webmaker"),
                                        ],
                                        help_text="Which newsletter(s) should be selectable? See <a href='https://www.mozilla.org/newsletter/newsletter-all.json'>Basket for details and available locales</a>",
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(default="Love the Web?", max_length=50)),
                                (
                                    "tagline",
                                    wagtail.blocks.CharBlock(default="Get the Mozilla newsletter and help us keep it open and free.", max_length=100),
                                ),
                                (
                                    "accompanying_image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                            (
                                                "decorative_only",
                                                wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                            ),
                                        ],
                                        help_text="NB: Needs to match background colour (for now - working on a no-image variation)",
                                        required=True,
                                    ),
                                ),
                                ("success_title", wagtail.blocks.CharBlock(default="Thanks!", max_length=50)),
                                (
                                    "success_message",
                                    wagtail.blocks.CharBlock(
                                        default="If you haven’t previously confirmed a subscription to a Mozilla-related newsletter you may have to do so. Please check your inbox or your spam filter for an email from us.",
                                        max_length=200,
                                    ),
                                ),
                            ],
                            help_text="General Mozilla newsletter signup form - no custom emailing, just signup via the Basket backend service",
                            label="Newsletter signup form",
                            label_format="Newsletter: {title}",
                            required=False,
                        ),
                    ),
                    (
                        "section_heading",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_level",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("h2", "Heading Level 2"), ("h3", "Heading Level 3"), ("h4", "Heading Level 4")],
                                        help_text="Remember to respect best practices around hierarchy of heading level: <a href='https://developer.mozilla.org/docs/Web/HTML/Element/Heading_Elements#usage_notes'>See MDN</a>",
                                    ),
                                ),
                                (
                                    "heading_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("", "Large"), ("mzp-u-title-md", "Medium"), ("mzp-u-title-sm", "Small")],
                                        help_text="Sets the display size of the heading independent of the heading level (h2, h3, or h4).",
                                        required=False,
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(blank=True, choices=[("", "Default"), ("t-align-center", "Center")], required=False),
                                ),
                                ("text", wagtail.blocks.TextBlock(max_length=120, required=True)),
                            ],
                            help_text=None,
                            label="Section heading",
                            label_format="Section heading: {text}",
                            required=False,
                        ),
                    ),
                    (
                        "split",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout_variant",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Standard"),
                                            ("mzp-l-split-reversed", "Reversed"),
                                            ("mzp-l-split-body-narrow", "Narrow body"),
                                            ("mzp-l-split-body-narrow mzp-l-split-reversed", "Narrow body, reversed"),
                                            ("mzp-l-split-body-wide", "Wide body"),
                                            ("mzp-l-split-body-wide mzp-l-split-reversed", "Wide body, reversed"),
                                            ("mzp-t-dark mzp-t-background-secondary", "Dark Background"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "content_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("mzp-t-content-md", "Medium"), ("mzp-t-content-lg", "Large"), ("mzp-t-content-xl", "Extra-large")],
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=120, required=True)),
                                ("text", wagtail.blocks.TextBlock(max_length=500, required=True)),
                                (
                                    "cta_button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                            (
                                                "decorative_only",
                                                wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/split--default.html'>Protocol docs for split</a>.  Not all options supported",
                            label="Split content",
                            label_format="Split: {title}",
                            required=False,
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [("video", wagtail.embeds.blocks.EmbedBlock(required=True))],
                            icon="media",
                            label="Video embed",
                            label_format="Video embed: {video}",
                            required=False,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
