# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-10-01 19:58

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0084_generalpurposepage_intro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalpurposepage",
            name="intro",
        ),
        migrations.AddField(
            model_name="generalpurposepage",
            name="introduction",
            field=wagtail.fields.RichTextField(blank=True, help_text="Optional intro for the page"),
        ),
    ]
