# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-10-01 20:24

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks

import common.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("microsite", "0085_remove_generalpurposepage_intro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLandingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page_layout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mzp-l-content mzp-t-content-sm", "Small"),
                            ("mzp-l-content mzp-t-content-md", "Medium"),
                            ("mzp-l-content mzp-t-content-lg", "Large"),
                            ("mzp-l-content mzp-t-content-xl", "Extra Large"),
                        ],
                        default="mzp-l-content mzp-t-content-lg",
                        help_text="Optional layout wrapper <i>– only for components that need one</i>. <a href='https://protocol.mozilla.org/components/detail/content-container--default.html'>Protocol docs for layout</a>.",
                        max_length=64,
                    ),
                ),
                (
                    "menu_description",
                    models.CharField(blank=True, help_text="Text to accompany an entry in the navigation menu. Optional.", max_length=200),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "main_heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="Up to 75 characters. Will be the H1 of the page it's used in", max_length=75, required=True
                                            ),
                                        ),
                                        ("subheading", wagtail.blocks.CharBlock(help_text="Up to 150 characters", max_length=150, required=False)),
                                        ("standfirst", wagtail.blocks.TextBlock(help_text="Up to 400 characters", max_length=400, required=False)),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Optional but recommended - needs to be something that will fill well", required=False
                                            ),
                                        ),
                                        (
                                            "call_to_action",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                    ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                    (
                                                        "rel",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                            max_length=100,
                                                            required=False,
                                                        ),
                                                    ),
                                                    ("label", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                ],
                                                help_text="Link for an optional button at the base of the hero",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            common.blocks.ColorBlock(
                                                help_text="For a solid block of colour, matched to the background image", required=True
                                            ),
                                        ),
                                        (
                                            "theme",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")],
                                                help_text="The dark theme works best with a dark background color selected, the light theme needs a light one.",
                                            ),
                                        ),
                                        (
                                            "layout",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[("hero-section-default", "Default layout"), ("hero-section-centered", "Centered layout")]
                                            ),
                                        ),
                                    ],
                                    help_text="Intended for use at top of the page. Works well with an SVG background image and appropriate color",
                                    label_format="Hero: {main_heading}",
                                    required=False,
                                ),
                            ),
                            (
                                "cards",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "layout",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("mzp-l-card-hero", "5-Card Hero layout"),
                                                    ("mzp-l-card-quarter", "4-Card Layout"),
                                                    ("mzp-l-card-third", "3-Card Layout"),
                                                    ("mzp-l-card-half", "2-Card Layout"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Card title with about 30-40 characters", max_length=60, required=False
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="A description of about 150 characters. Usually we only have room for one or two sentences.",
                                                                max_length=170,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "cta",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Call to action with about 30-40 characters", max_length=60, required=False
                                                            ),
                                                        ),
                                                        (
                                                            "meta_info",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Meta info at the base of the card", max_length=60, required=False
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                                    ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                                    (
                                                                        "rel",
                                                                        wagtail.blocks.CharBlock(
                                                                            help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                                            max_length=100,
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("mzp-c-card-extra-small", "Extra small"),
                                                                    ("", "Small"),
                                                                    ("mzp-c-card-extra-medium", "Medium"),
                                                                    ("mzp-c-card-large", "Large"),
                                                                    ("mzp-c-card-extra-large", "Extra Large"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image_aspect_ratio",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("mzp-has-aspect-1-1", "1:1"),
                                                                    ("mzp-has-aspect-3-2", "3:2"),
                                                                    ("mzp-has-aspect-16-9", "16:9"),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "card_image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Alt-text for this image", max_length=250, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "decorative_only",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False, label="Is this image decorative only?", required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        ("tag", wagtail.blocks.CharBlock(max_length=48, required=False)),
                                                    ]
                                                ),
                                                collapsed=True,
                                                help_text="<a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                                            ),
                                        ),
                                    ],
                                    help_text="Layout wrapper for Cards. <a href='https://protocol.mozilla.org/components/detail/card-layout--overview.html'>Protocol docs for card-layout</a>.",
                                    label="Card group",
                                    label_format="Card group",
                                    required=False,
                                ),
                            ),
                            (
                                "columns",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                        (
                                            "column_layout",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("mzp-l-content", "One column"),
                                                    ("mzp-l-content mzp-l-columns mzp-t-columns-two", "Two column"),
                                                    ("mzp-l-content mzp-l-columns mzp-t-columns-three", "Three column"),
                                                    ("mzp-l-content mzp-l-columns mzp-t-columns-four", "Four column"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            common.blocks.ColorBlock(
                                                help_text="For a solid block of colour. Use with a light/dark theme as appropriate, to ensure text is visible.",
                                                required=True,
                                            ),
                                        ),
                                        ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                                        (
                                            "content",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "stack_of_pictos",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                ("title", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                (
                                                                    "pictos",
                                                                    wagtail.blocks.ListBlock(
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "layout",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        choices=[
                                                                                            ("", "Standard"),
                                                                                            ("mzp-t-picto-center", "Centered"),
                                                                                            ("mzp-t-picto-side", "Side"),
                                                                                        ],
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "image",
                                                                                    wagtail.blocks.StructBlock(
                                                                                        [
                                                                                            (
                                                                                                "image",
                                                                                                wagtail.images.blocks.ImageChooserBlock(
                                                                                                    required=False
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "alt_text",
                                                                                                wagtail.blocks.CharBlock(
                                                                                                    label="Alt-text for this image",
                                                                                                    max_length=250,
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "decorative_only",
                                                                                                wagtail.blocks.BooleanBlock(
                                                                                                    default=False,
                                                                                                    label="Is this image decorative only?",
                                                                                                    required=False,
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                                ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                                (
                                                                                    "body",
                                                                                    wagtail.blocks.TextBlock(
                                                                                        help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                                        max_length=150,
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                        collapsed=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "picto",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "layout",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            ("", "Standard"),
                                                                            ("mzp-t-picto-center", "Centered"),
                                                                            ("mzp-t-picto-side", "Side"),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                            (
                                                                                "alt_text",
                                                                                wagtail.blocks.CharBlock(
                                                                                    label="Alt-text for this image", max_length=250, required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "decorative_only",
                                                                                wagtail.blocks.BooleanBlock(
                                                                                    default=False,
                                                                                    label="Is this image decorative only?",
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.TextBlock(
                                                                        help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                        max_length=150,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "picto_with_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "layout",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            ("", "Standard"),
                                                                            ("mzp-t-picto-center", "Centered"),
                                                                            ("mzp-t-picto-side", "Side"),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                            (
                                                                                "alt_text",
                                                                                wagtail.blocks.CharBlock(
                                                                                    label="Alt-text for this image", max_length=250, required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "decorative_only",
                                                                                wagtail.blocks.BooleanBlock(
                                                                                    default=False,
                                                                                    label="Is this image decorative only?",
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.TextBlock(
                                                                        help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                        max_length=150,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "link",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                                            (
                                                                                "external_url",
                                                                                wagtail.blocks.URLBlock(label="External URL", required=False),
                                                                            ),
                                                                            (
                                                                                "rel",
                                                                                wagtail.blocks.CharBlock(
                                                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                                                    max_length=100,
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                            ("label", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                        ],
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ],
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.RichTextBlock(
                                                            features=["h3", "h4", "bold", "italic", "strikethrough", "link", "ol", "ul"]
                                                        ),
                                                    ),
                                                ],
                                                help_text="Only blocks that can fit/flow well in a multi-column layout are allowed here - e.g. Picto",
                                            ),
                                        ),
                                    ],
                                    help_text="Column layout wrapper: <a href='https://protocol.mozilla.org/components/detail/columns--overview.html'>Protocol docs for columns</a>.. Has Picto sub-components: <a href='https://protocol.mozilla.org/components/detail/picto--default.html'>Protocol docs for picto</a>.",
                                    label="Column block",
                                    label_format="Column block: {column_layout}",
                                    required=False,
                                ),
                            ),
                            (
                                "callout",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "headline",
                                            wagtail.blocks.CharBlock(help_text="Around 50 chars ideally. Max 100", max_length=100, required=True),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.TextBlock(help_text="Around 150 chars ideally. Max 300", max_length=300, required=True),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                    ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                    (
                                                        "rel",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                            max_length=100,
                                                            required=False,
                                                        ),
                                                    ),
                                                    ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                                ],
                                                required=True,
                                            ),
                                        ),
                                        ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                                    ],
                                    help_text="<a href='https://protocol.mozilla.org/components/detail/call-out--default.html'>Protocol docs for callout</a>.",
                                    label_format="Callout: {headline}",
                                    required=False,
                                ),
                            ),
                            (
                                "compact_callout",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "headline",
                                            wagtail.blocks.CharBlock(help_text="Around 50 chars ideally. Max 100", max_length=100, required=True),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.TextBlock(help_text="Around 150 chars ideally. Max 300", max_length=300, required=True),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                    ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                    (
                                                        "rel",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                            max_length=100,
                                                            required=False,
                                                        ),
                                                    ),
                                                    ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                                ],
                                                required=True,
                                            ),
                                        ),
                                        ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                                    ],
                                    help_text="<a href='https://protocol.mozilla.org/components/detail/compact-call-out--default.html'>Protocol docs for compact-callout</a>.",
                                    label_format="Compact callout: {headline}",
                                    required=False,
                                ),
                            ),
                            (
                                "split",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "layout_variant",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Standard"),
                                                    ("mzp-l-split-reversed", "Reversed"),
                                                    ("mzp-l-split-body-narrow", "Narrow body"),
                                                    ("mzp-l-split-body-narrow mzp-l-split-reversed", "Narrow body, reversed"),
                                                    ("mzp-l-split-body-wide", "Wide body"),
                                                    ("mzp-l-split-body-wide mzp-l-split-reversed", "Wide body, reversed"),
                                                    ("mzp-t-dark mzp-t-background-secondary", "Dark Background"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "content_size",
                                            wagtail.blocks.ChoiceBlock(
                                                blank=True,
                                                choices=[
                                                    ("mzp-t-content-md", "Medium"),
                                                    ("mzp-t-content-lg", "Large"),
                                                    ("mzp-t-content-xl", "Extra-large"),
                                                ],
                                            ),
                                        ),
                                        ("title", wagtail.blocks.CharBlock(max_length=120, required=True)),
                                        ("text", wagtail.blocks.TextBlock(max_length=500, required=True)),
                                        (
                                            "cta_button",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                    ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                    (
                                                        "rel",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                            max_length=100,
                                                            required=False,
                                                        ),
                                                    ),
                                                    ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                    (
                                                        "alt_text",
                                                        wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False),
                                                    ),
                                                    (
                                                        "decorative_only",
                                                        wagtail.blocks.BooleanBlock(
                                                            default=False, label="Is this image decorative only?", required=False
                                                        ),
                                                    ),
                                                ],
                                                required=True,
                                            ),
                                        ),
                                    ],
                                    help_text="Flexible short text + image component. <a href='https://protocol.mozilla.org/components/detail/split--default.html'>Protocol docs for split</a>. Not all options supported",
                                    label="Split content",
                                    label_format="Split: {title}",
                                    required=False,
                                ),
                            ),
                            (
                                "video",
                                wagtail.blocks.StructBlock(
                                    [("video", wagtail.embeds.blocks.EmbedBlock(required=True))],
                                    help_text="In alpha - minimal/simple embedding at the moment. No in-page transcript support.",
                                    icon="media",
                                    label="Video embed",
                                    label_format="Video embed: {video}",
                                    required=False,
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "menu_icon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Icon to accompany an entry in the navigation menu. Optional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
