# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-10-01 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("microsite", "0086_productlandingpage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductLandingPage",
            new_name="ProductPage",
        ),
    ]
