# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0094_alter_generalpurposepage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="faqpage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="generalpurposepage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="innovationscontentpage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="longformarticlepage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="productpage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="protocoltestpage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
        migrations.AddField(
            model_name="structuralpage",
            name="show_breadcrumbs",
            field=models.BooleanField(
                default=False,
                help_text="Automatically show <a href='https://protocol.mozilla.org/components/detail/breadcrumb'>breadcrumbs</a> on this page, if appropriate?",
            ),
        ),
    ]
