# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.5 on 2023-10-19 10:09

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("microsite", "0097_alter_generalpurposepage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="longformarticlepage",
            name="aftermatter",
            field=wagtail.fields.StreamField(
                [
                    (
                        "callout",
                        wagtail.blocks.StructBlock(
                            [
                                ("headline", wagtail.blocks.CharBlock(help_text="Around 50 chars ideally. Max 100", max_length=100, required=True)),
                                ("body", wagtail.blocks.TextBlock(help_text="Around 150 chars ideally. Max 400", max_length=400, required=True)),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=True,
                                    ),
                                ),
                                ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/compact-call-out--default.html'>Protocol docs for compact-callout</a>.",
                            label_format="Compact callout: {headline}",
                            required=False,
                        ),
                    ),
                    (
                        "compact_callout",
                        wagtail.blocks.StructBlock(
                            [
                                ("headline", wagtail.blocks.CharBlock(help_text="Around 50 chars ideally. Max 100", max_length=100, required=True)),
                                ("body", wagtail.blocks.TextBlock(help_text="Around 150 chars ideally. Max 400", max_length=400, required=True)),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=True,
                                    ),
                                ),
                                ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/compact-call-out--default.html'>Protocol docs for compact-callout</a>.",
                            label_format="Compact callout: {headline}",
                            required=False,
                        ),
                    ),
                    (
                        "split",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout_variant",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Standard"),
                                            ("mzp-l-split-reversed", "Reversed"),
                                            ("mzp-l-split-body-narrow", "Narrow body"),
                                            ("mzp-l-split-body-narrow mzp-l-split-reversed", "Narrow body, reversed"),
                                            ("mzp-l-split-body-wide", "Wide body"),
                                            ("mzp-l-split-body-wide mzp-l-split-reversed", "Wide body, reversed"),
                                            ("mzp-t-dark mzp-t-background-secondary", "Dark Background"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "content_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("mzp-t-content-md", "Medium"), ("mzp-t-content-lg", "Large"), ("mzp-t-content-xl", "Extra-large")],
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=120, required=True)),
                                ("text", wagtail.blocks.TextBlock(max_length=500, required=True)),
                                (
                                    "cta_button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                            (
                                                "decorative_only",
                                                wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/split--default.html'>Protocol docs for split</a>. - most, but not all, options are supported",
                            label="Split content",
                            label_format="Split: {title}",
                            required=False,
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
