name: Push main to stage
on: workflow_dispatch
permissions:
  contents: write
jobs:
  push-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git push
        run: |
          git push origin main:stage
