name: Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          pip install -r requirements/production.txt
          pip install -r requirements/test.txt
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install js dependencies and build assets
        run: |
          npm ci
          npm run build
      - name: Collect staticfiles
        run: python birdbox/manage.py collectstatic
      - name: Run tests
        run: >-
          DJANGO_SETTINGS_MODULE=birdbox.settings.test
          BASKET_NEWSLETTER_DATA_DO_SYNC=false
          pytest birdbox
  docker-build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Ensure docker containers build
        run: docker build .
